[package]
name = "zuma"
version = "0.1.0"
authors = ["Vladimír Ctibor <vladimir.ctibor@gmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.19.4"

[dependencies]
lalrpop-util = "0.19.4"
regex = "1.0"
anyhow = "1.0"